# Generated by Django 3.2.8 on 2021-10-22 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20211021_0345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('author',)},
        ),
    ]
